### ISSUE TITLE
Applicable License?

### ISSUE THREAD

**Issue by yashkhatri** [labra/SRDF#2]
There are different licences mentioned on the Github and bintray for this module.

On GitHub it's GNU LESSER GENERAL PUBLIC LICENSE Version 3, 29 June 2007
https://github.com/labra/SRDF/blob/master/LICENSE

While on Bintray it's MPL 2.0
https://bintray.com/labra/maven/srdf

Can you please look into it? 

/Yash

**Comment by labra** [comment]
Thanks for pointing it. I have changed the LICENSE file to MIT. 

Nevertheless the code in this repository is not maintained at this moment. 

The code was included as a [module](https://github.com/labra/shaclex/tree/master/modules/srdf) in the [shaclex repository](https://github.com/labra/shaclex) and that's the code that is published in bintray.

**Comment by yashkhatri** [comment]
Shouldn't it be fixed on bintray as well? It says MPL-2.0 license there. 
https://bintray.com/labra/maven/srdf

/Yash
